# Extensions and common functions
common.sql

# Accounts
account/account_data_structure.sql
account/account_functions.sql

# Users
app_user/app_user_data_structure.sql
app_user/app_user_functions.sql

# Spaces
space/space_data_structure.sql
space/space_functions.sql

# Markdown
md/md_functions.sql

# Documents
document/document_data_structure.sql
document/document_functions.sql
document/document_section_functions.sql
document/document_link_functions.sql

# Labels
label/label_data_structure.sql
label/label_functions.sql

# Categories
requirement/category_data_structure.sql

# Requirements
requirement/requirement_data_structure.sql
requirement/requirement_functions.sql

# Attachments
attachment/attachment_data_structure.sql

# Boards
board/board_data_structure.sql

# Journals
journal/journal_data_structure.sql

# Agents
agent/agent_data_structure.sql

# Initialization
init_system.sql
